In [1]:
#!pip install pandas-profiling

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df=pd.read_csv('Homeprice_Prediction.csv')
#pd.set_option('display.max_rows', df.shape[0] + 1)
df

area  bedroom  age          price
0   6000        5   30  913690.516649
1   3500        2   19  598916.668555
2   4200        6   50  670732.643058
3   2100       10   28  600054.829282
4   3400        4   32  592475.851704
5   5000        6   28  831480.390602
6   2000        2   21  424359.569824
7   2600        3   50  421266.095717
8   4100        3   46  602286.630265
9   4500        5    8  816694.647726
10  3900        4   18  693751.123396
11  6200        4   10  977348.483132
12  4390        6   12  814829.787555

In [4]:
#import pandas_profiling as pp
#pp.ProfileReport(df)

In [5]:
df.shape

(13, 4)

In [6]:
df.isnull().sum()

area       0
bedroom    0
age        0
price      0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   area     13 non-null     int64  
 1   bedroom  13 non-null     int64  
 2   age      13 non-null     int64  
 3   price    13 non-null     float64
dtypes: float64(1), int64(3)
memory usage: 544.0 bytes


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X = df.drop(['price'], axis = 1)
X

area  bedroom  age
0   6000        5   30
1   3500        2   19
2   4200        6   50
3   2100       10   28
4   3400        4   32
5   5000        6   28
6   2000        2   21
7   2600        3   50
8   4100        3   46
9   4500        5    8
10  3900        4   18
11  6200        4   10
12  4390        6   12

In [10]:
y = df.price
y

0     913690.516649
1     598916.668555
2     670732.643058
3     600054.829282
4     592475.851704
5     831480.390602
6     424359.569824
7     421266.095717
8     602286.630265
9     816694.647726
10    693751.123396
11    977348.483132
12    814829.787555
Name: price, dtype: float64

In [11]:

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

X_train

area  bedroom  age
8   4100        3   46
5   5000        6   28
2   4200        6   50
1   3500        2   19
12  4390        6   12
4   3400        4   32
7   2600        3   50
10  3900        4   18
3   2100       10   28
6   2000        2   21

In [12]:
from sklearn import linear_model
reg=linear_model.LinearRegression()

In [13]:
reg.fit(X_train, y_train)

LinearRegression()

In [14]:
y_predicted = reg.predict(X_test)
y_predicted

array([977348.48313208, 816694.64772565, 913690.51664893])

In [15]:
#train = reg.predict(X_train)
#train

In [16]:
y_test

11    977348.483132
9     816694.647726
0     913690.516649
Name: price, dtype: float64

In [17]:
from sklearn import metrics

In [18]:
#metrics.accuracy_score(y_test,y_predicted)
#metrics.f1_score(y_test,y_predicted)

In [19]:
import math

In [20]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [21]:
#MSE = metrics.mean_squared_error(y_test, y_predicted)
#MSE

In [22]:
rmse = math.sqrt(mean_squared_error(y_test,y_predicted))
rmse

1.2436658511158102e-08

In [23]:
r2_score(y_test, y_predicted)

1.0

In [24]:
#reg.score(X_test, y_test)

In [25]:
reg.predict([[3000, 4, 40]])

array([521797.13165824])

In [26]:
arr = np.array([[3000, 4, 40], [4000, 8, 40], [2000, 2, 10]])
reg.predict(arr)

array([521797.13165824, 727415.09391214, 459908.46681921])

In [33]:
#one can also use a dictionary
new_area = pd.DataFrame({
    'area' : [3000, 4000, 2000],
    'bedroom' : [4, 8, 2],
    'age' : [40, 40, 10]
})

Price = reg.predict(new_area)
Price

array([521797.13165824, 727415.09391214, 459908.46681921])

In [ ]:
array = Price
array

In [ ]:
aa = pd.DataFrame(array, columns = ['price'])
aa

In [ ]:
conc = pd.concat([new_area, aa], axis = 1)
conc

In [ ]:
new_df = pd.concat([df, conc], ignore_index = True)
new_df

In [ ]:
# Saving as csv file 
new_df.to_csv('MyCsvFile.csv')